networks:
  default:
    external: true
    name: ddev_default
services:
  db:
    build:
      args:
        BASE_IMAGE: drud/ddev-dbserver-mariadb-10.2:v1.15.0
        gid: '20'
        uid: '502'
        username: byreshb
      context: /Users/byreshb/apps/php/my-drupal8-site/.ddev/db-build
      dockerfile: /Users/byreshb/apps/php/my-drupal8-site/.ddev/.dbimageBuild/Dockerfile
    command: ''
    container_name: ddev-my-drupal8-site-db
    environment:
      COLUMNS: '238'
      DDEV_PROJECT: my-drupal8-site
      LINES: '55'
      TZ: ''
    healthcheck:
      interval: 1s
      retries: 30
      start_period: 20s
      timeout: 2m
    hostname: my-drupal8-site-db
    image: drud/ddev-dbserver-mariadb-10.2:v1.15.0-my-drupal8-site-built
    labels:
      com.ddev.app-type: drupal8
      com.ddev.approot: /Users/byreshb/apps/php/my-drupal8-site
      com.ddev.platform: ddev
      com.ddev.site-name: my-drupal8-site
    ports:
    - 127.0.0.1::3306/tcp
    restart: "no"
    stop_grace_period: 60s
    user: '502:20'
    volumes:
    - source: mariadb-database
      target: /var/lib/mysql
      type: volume
      volume:
        nocopy: true
    - source: /Users/byreshb/apps/php/my-drupal8-site/.ddev
      target: /mnt/ddev_config
      type: bind
    - ddev-global-cache:/mnt/ddev-global-cache:rw
  dba:
    container_name: ddev-my-drupal8-site-dba
    environment:
      HTTPS_EXPOSE: 8037:8036
      HTTP_EXPOSE: 8036:8036
      PMA_PASSWORD: db
      PMA_USER: db
      TZ: ''
      UPLOAD_LIMIT: 1024M
      VIRTUAL_HOST: my-drupal8-site.ddev.site
    healthcheck:
      interval: 2m
      retries: 1
      timeout: 2s
    hostname: my-drupal8-site-dba
    image: phpmyadmin/phpmyadmin:5
    labels:
      com.ddev.app-type: drupal8
      com.ddev.approot: /Users/byreshb/apps/php/my-drupal8-site
      com.ddev.platform: ddev
      com.ddev.site-name: my-drupal8-site
    links:
    - db:db
    ports:
    - target: 80
    restart: "no"
  web:
    build:
      args:
        BASE_IMAGE: drud/ddev-webserver:v1.15.0
        gid: '20'
        uid: '502'
        username: byreshb
      context: /Users/byreshb/apps/php/my-drupal8-site/.ddev/web-build
      dockerfile: /Users/byreshb/apps/php/my-drupal8-site/.ddev/.webimageBuild/Dockerfile
    cap_add:
    - SYS_PTRACE
    container_name: ddev-my-drupal8-site-web
    environment:
      COLUMNS: '238'
      DDEV_PHP_VERSION: '7.3'
      DDEV_PROJECT: my-drupal8-site
      DDEV_PROJECT_TYPE: drupal8
      DDEV_ROUTER_HTTPS_PORT: '443'
      DDEV_ROUTER_HTTP_PORT: '8000'
      DDEV_WEBSERVER_TYPE: nginx-fpm
      DDEV_XDEBUG_ENABLED: "false"
      DEPLOY_NAME: local
      DOCKER_IP: 127.0.0.1
      DOCROOT: web
      DRUSH_OPTIONS_URI: http://my-drupal8-site.ddev.site:8000
      HOST_DOCKER_INTERNAL_IP: ''
      HTTPS_EXPOSE: 443:80,8026:8025
      HTTP_EXPOSE: 8000:80,8025:8025
      IS_DDEV_PROJECT: "true"
      LINES: '55'
      PHP_IDE_CONFIG: serverName=my-drupal8-site.ddev.site
      SSH_AUTH_SOCK: /home/.ssh-agent/socket
      TZ: ''
      VIRTUAL_HOST: my-drupal8-site.ddev.site
    external_links:
    - ddev-router:my-drupal8-site.ddev.site
    healthcheck:
      interval: 1s
      retries: 20
      start_period: 20s
      timeout: 2m
    hostname: my-drupal8-site-web
    image: drud/ddev-webserver:v1.15.0-my-drupal8-site-built
    labels:
      com.ddev.app-type: drupal8
      com.ddev.approot: /Users/byreshb/apps/php/my-drupal8-site
      com.ddev.platform: ddev
      com.ddev.site-name: my-drupal8-site
    links:
    - db:db
    ports:
    - 127.0.0.1::80/tcp
    - 127.0.0.1::443/tcp
    restart: "no"
    user: '502:20'
    volumes:
    - consistency: cached
      source: /Users/byreshb/apps/php/my-drupal8-site
      target: /var/www/html
      type: bind
    - /Users/byreshb/apps/php/my-drupal8-site/.ddev:/mnt/ddev_config:ro
    - /Users/byreshb/apps/php/my-drupal8-site/.ddev/nginx_full:/etc/nginx/sites-enabled:ro
    - /Users/byreshb/apps/php/my-drupal8-site/.ddev/apache:/etc/apache2/sites-enabled:ro
    - ddev-global-cache:/mnt/ddev-global-cache:rw
    - ddev-ssh-agent_socket_dir:/home/.ssh-agent:rw
version: '3.6'
volumes:
  ddev-global-cache:
    name: ddev-global-cache
  ddev-ssh-agent_socket_dir:
    external: true
    name: ddev-ssh-agent_socket_dir
  mariadb-database:
    name: my-drupal8-site-mariadb

